AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: provided.al2
    MemorySize: 256
    Architectures:
      - x86_64
    Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html

Resources:
  EveryNotePersisterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      NoteTableConnector:
        Properties:
          Destination:
            Id: NoteTable
          Permissions:
            - Read
            - Write

    Properties:
      CodeUri: .
      Handler: none
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MainSqs.Arn
            BatchSize: 10
            Enabled: true
    Metadata:
      BuildMethod: makefile

  MainSqs:
    Type: AWS::SQS::Queue

  NoteTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Note
      PrimaryKey:
        Name: id
        Type: String

