spring:
  jackson:
    mapper:
      accept-case-insensitive-properties: true #This property is needed due to JSON messages sent by SQS (i.e. the $.Records filed starts with a capital letter)
    deserialization:
      fail-on-unknown-properties: false #Ignore all unnecessary properties

