on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: "Check if build image exists"
        id: check_image
        run: |
          if [ "$(docker images -q al2-graalvm:gradle 2> /dev/null)" == "" ]; then
            echo "Image not found. Building image."
            exit 1
          else
            echo "Image found. Skipping build."
            exit 0
      - name: Build the Docker Image
        if: steps.check_image.outputs.exit_code == '1'
        run: ./build-image.sh

      # Build inside Docker containers
      - run: sam build --use-container
      # Prevent prompts and failure when the stack is unchanged
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset