on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: "Gradle Build"
        run: ./gradlew build -x test

      - name: "Gradle Test"
        run: ./gradlew test

  create_native_binary:
    name: "Create Native binary"
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Build Native image"
        run: |
          mkdir lambda
          docker build -t native-lambda:1 .
          id=$(docker create --name tmp native-lambda:1)
          docker cp $id:/app/lambda.zip ./lambda/lambda.zip
          docker rm tmp

      - uses: actions/upload-artifact@v3
        with:
          name: lambda_${{github.sha}}
          path: ./lambda
